{:config {:order 0, :description "Tutorial Recording", :name :tutorial}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:value [:main :my-counter] nil 1]
  [:transform-enable [:main :my-counter] :inc [{:io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 4]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 1.33]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 2]
  [:node-create [:main :other-counters] :map]
  [:node-create [:main :other-counters "abc"] :map]
  [:value [:main :other-counters "abc"] nil 2]
  [:node-create [:main :other-counters "xyz"] :map]
  [:value [:main :other-counters "xyz"] nil 1]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 46]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 18]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 26]
  :break
  [:value [:main :other-counters "abc"] 2 3]
  [:value [:main :total-count] 4 5]
  [:value [:main :average-count] 1.33 1.67]
  [:value [:main :max-count] 2 3]
  [:value [:pedestal :debug :dataflow-time] 18 16]
  [:value [:pedestal :debug :dataflow-time-avg] 26 24]
  :break
  [:value [:main :other-counters "xyz"] 1 2]
  [:value [:main :total-count] 5 6]
  [:value [:main :average-count] 1.67 2]
  [:value [:pedestal :debug :dataflow-time] 16 17]
  [:value [:pedestal :debug :dataflow-time-avg] 24 23]
  :break
  [:value [:main :other-counters "abc"] 3 4]
  [:value [:main :total-count] 6 7]
  [:value [:main :average-count] 2 2.33]
  [:value [:main :max-count] 3 4]
  [:value [:pedestal :debug :dataflow-time] 17 15]
  [:value [:pedestal :debug :dataflow-time-avg] 23 21]
  :break
  [:value [:main :other-counters "abc"] 4 5]
  [:value [:main :total-count] 7 8]
  [:value [:main :average-count] 2.33 2.67]
  [:value [:main :max-count] 4 5]
  [:value [:pedestal :debug :dataflow-time] 15 26]
  [:value [:pedestal :debug :dataflow-time-avg] 21 22]
  :break
  [:value [:main :other-counters "xyz"] 2 3]
  [:value [:main :total-count] 8 9]
  [:value [:main :average-count] 2.67 3]
  [:value [:pedestal :debug :dataflow-time] 26 17]
  [:value [:pedestal :debug :dataflow-time-avg] 22 21]
  :break
  [:value [:main :other-counters "abc"] 5 6]
  [:value [:main :total-count] 9 10]
  [:value [:main :average-count] 3 3.33]
  [:value [:main :max-count] 5 6]
  [:value [:pedestal :debug :dataflow-time] 17 19]
  :break
  [:value [:main :other-counters "abc"] 6 7]
  [:value [:main :total-count] 10 11]
  [:value [:main :average-count] 3.33 3.67]
  [:value [:main :max-count] 6 7]
  [:value [:pedestal :debug :dataflow-time] 19 17]
  :break
  [:value [:main :total-count] 11 12]
  [:value [:main :average-count] 3.67 4]
  [:value [:main :my-counter] 1 2]
  [:value [:pedestal :debug :dataflow-time] 17 14]
  [:value [:pedestal :debug :dataflow-time-avg] 21 20]
  :break
  [:value [:main :total-count] 12 13]
  [:value [:main :average-count] 4 4.33]
  [:value [:main :my-counter] 2 3]
  [:value [:pedestal :debug :dataflow-time] 14 16]
  :break
  [:value [:main :total-count] 13 14]
  [:value [:main :average-count] 4.33 4.67]
  [:value [:main :my-counter] 3 4]
  [:value [:pedestal :debug :dataflow-time] 16 13]
  [:value [:pedestal :debug :dataflow-time-avg] 20 19]
  :break
  [:value [:main :total-count] 14 15]
  [:value [:main :average-count] 4.67 5]
  [:value [:main :my-counter] 4 5]
  :break
  [:value [:main :total-count] 15 16]
  [:value [:main :average-count] 5 5.33]
  [:value [:main :my-counter] 5 6]
  [:value [:pedestal :debug :dataflow-time] 13 15]
  :break
  [:value [:main :total-count] 16 17]
  [:value [:main :average-count] 5.33 5.67]
  [:value [:main :my-counter] 6 7]
  [:value [:pedestal :debug :dataflow-time] 15 23]
  :break
  [:value [:main :other-counters "abc"] 7 8]
  [:value [:main :total-count] 17 18]
  [:value [:main :average-count] 5.67 6]
  [:value [:main :max-count] 7 8]
  [:value [:pedestal :debug :dataflow-time] 23 17]
  :break
  [:value [:main :total-count] 18 19]
  [:value [:main :average-count] 6 6.33]
  [:value [:main :my-counter] 7 8]
  [:value [:pedestal :debug :dataflow-time] 17 14]
  :break
  [:value [:main :total-count] 19 20]
  [:value [:main :average-count] 6.33 6.67]
  [:value [:main :max-count] 8 9]
  [:value [:main :my-counter] 8 9]
  [:value [:pedestal :debug :dataflow-time] 14 15]
  [:value [:pedestal :debug :dataflow-time-avg] 19 18]
  :break
  [:value [:main :total-count] 20 21]
  [:value [:main :average-count] 6.67 7]
  [:value [:main :max-count] 9 10]
  [:value [:main :my-counter] 9 10]
  :break
  [:value [:main :other-counters "xyz"] 3 4]
  [:value [:main :total-count] 21 22]
  [:value [:main :average-count] 7 7.33]
  [:value [:pedestal :debug :dataflow-time] 15 13]
 ]}